AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  An Amazon S3 trigger that retrieves metadata for the object that has been
  updated.
Resources:
  test10:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: >-
        An Amazon S3 trigger that retrieves metadata for the object that has
        been updated.
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::017784105438:role/test-Lambda-S3'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /test10
            Method: ANY
      Tags:
        'lambda-console:blueprint': s3-get-object-python
